// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/film/film-service.proto

package film_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FilmCategory struct {
	//id of the film
	FilmId int64 `protobuf:"varint,1,opt,name=film_id,json=filmId,proto3" json:"film_id,omitempty"`
	//title of the film
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	//Description of the film
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	//Release year of the film
	ReleaseYear string `protobuf:"bytes,4,opt,name=release_year,json=releaseYear,proto3" json:"release_year,omitempty"`
	//Foreign key from Language entity
	LanguageId int64 `protobuf:"varint,5,opt,name=language_id,json=languageId,proto3" json:"language_id,omitempty"`
	//Optional parameter of original language
	OriginalLanguageId int64 `protobuf:"varint,6,opt,name=original_language_id,json=originalLanguageId,proto3" json:"original_language_id,omitempty"`
	//Rental duration of film
	RentalDuration string `protobuf:"bytes,7,opt,name=rental_duration,json=rentalDuration,proto3" json:"rental_duration,omitempty"`
	//Rental rate of film
	RentalRate string `protobuf:"bytes,8,opt,name=rental_rate,json=rentalRate,proto3" json:"rental_rate,omitempty"`
	//The length of film
	Length int64 `protobuf:"varint,9,opt,name=length,proto3" json:"length,omitempty"`
	//Cost of the replacement
	ReplacementCost string `protobuf:"bytes,10,opt,name=replacement_cost,json=replacementCost,proto3" json:"replacement_cost,omitempty"`
	//Rating of the film
	Rating string `protobuf:"bytes,11,opt,name=rating,proto3" json:"rating,omitempty"`
	//Some special effects
	SpecialFeatures string `protobuf:"bytes,12,opt,name=special_features,json=specialFeatures,proto3" json:"special_features,omitempty"`
	//last update of Film entity
	LastUpdate           *timestamp.Timestamp `protobuf:"bytes,13,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *FilmCategory) Reset()         { *m = FilmCategory{} }
func (m *FilmCategory) String() string { return proto.CompactTextString(m) }
func (*FilmCategory) ProtoMessage()    {}
func (*FilmCategory) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{0}
}

func (m *FilmCategory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilmCategory.Unmarshal(m, b)
}
func (m *FilmCategory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilmCategory.Marshal(b, m, deterministic)
}
func (m *FilmCategory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilmCategory.Merge(m, src)
}
func (m *FilmCategory) XXX_Size() int {
	return xxx_messageInfo_FilmCategory.Size(m)
}
func (m *FilmCategory) XXX_DiscardUnknown() {
	xxx_messageInfo_FilmCategory.DiscardUnknown(m)
}

var xxx_messageInfo_FilmCategory proto.InternalMessageInfo

func (m *FilmCategory) GetFilmId() int64 {
	if m != nil {
		return m.FilmId
	}
	return 0
}

func (m *FilmCategory) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FilmCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FilmCategory) GetReleaseYear() string {
	if m != nil {
		return m.ReleaseYear
	}
	return ""
}

func (m *FilmCategory) GetLanguageId() int64 {
	if m != nil {
		return m.LanguageId
	}
	return 0
}

func (m *FilmCategory) GetOriginalLanguageId() int64 {
	if m != nil {
		return m.OriginalLanguageId
	}
	return 0
}

func (m *FilmCategory) GetRentalDuration() string {
	if m != nil {
		return m.RentalDuration
	}
	return ""
}

func (m *FilmCategory) GetRentalRate() string {
	if m != nil {
		return m.RentalRate
	}
	return ""
}

func (m *FilmCategory) GetLength() int64 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *FilmCategory) GetReplacementCost() string {
	if m != nil {
		return m.ReplacementCost
	}
	return ""
}

func (m *FilmCategory) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *FilmCategory) GetSpecialFeatures() string {
	if m != nil {
		return m.SpecialFeatures
	}
	return ""
}

func (m *FilmCategory) GetLastUpdate() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdate
	}
	return nil
}

//Request data to create new film category
type CreateRequest struct {
	//Api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	//Film category entity to add to database
	FilmCategory         *FilmCategory `protobuf:"bytes,2,opt,name=film_category,json=filmCategory,proto3" json:"film_category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateRequest) Reset()         { *m = CreateRequest{} }
func (m *CreateRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()    {}
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{1}
}

func (m *CreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRequest.Unmarshal(m, b)
}
func (m *CreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRequest.Marshal(b, m, deterministic)
}
func (m *CreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRequest.Merge(m, src)
}
func (m *CreateRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRequest.Size(m)
}
func (m *CreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRequest proto.InternalMessageInfo

func (m *CreateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateRequest) GetFilmCategory() *FilmCategory {
	if m != nil {
		return m.FilmCategory
	}
	return nil
}

//Response message of created film category
type CreateResponse struct {
	//APi version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	//We get id of film category
	Film                 int64    `protobuf:"varint,2,opt,name=film,proto3" json:"film,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *CreateResponse) GetFilm() int64 {
	if m != nil {
		return m.Film
	}
	return 0
}

//Request message request for get data about film category
type ReadMessage struct {
	//api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	//Get film category by id
	FilmId               int64    `protobuf:"varint,2,opt,name=film_id,json=filmId,proto3" json:"film_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadMessage) Reset()         { *m = ReadMessage{} }
func (m *ReadMessage) String() string { return proto.CompactTextString(m) }
func (*ReadMessage) ProtoMessage()    {}
func (*ReadMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{3}
}

func (m *ReadMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadMessage.Unmarshal(m, b)
}
func (m *ReadMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadMessage.Marshal(b, m, deterministic)
}
func (m *ReadMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadMessage.Merge(m, src)
}
func (m *ReadMessage) XXX_Size() int {
	return xxx_messageInfo_ReadMessage.Size(m)
}
func (m *ReadMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ReadMessage proto.InternalMessageInfo

func (m *ReadMessage) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadMessage) GetFilmId() int64 {
	if m != nil {
		return m.FilmId
	}
	return 0
}

//Response message about film
type ReadResponse struct {
	//api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	//Film entity read by id
	FilmCategory         *FilmCategory `protobuf:"bytes,2,opt,name=film_category,json=filmCategory,proto3" json:"film_category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReadResponse) Reset()         { *m = ReadResponse{} }
func (m *ReadResponse) String() string { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()    {}
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{4}
}

func (m *ReadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadResponse.Unmarshal(m, b)
}
func (m *ReadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadResponse.Marshal(b, m, deterministic)
}
func (m *ReadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadResponse.Merge(m, src)
}
func (m *ReadResponse) XXX_Size() int {
	return xxx_messageInfo_ReadResponse.Size(m)
}
func (m *ReadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadResponse proto.InternalMessageInfo

func (m *ReadResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadResponse) GetFilmCategory() *FilmCategory {
	if m != nil {
		return m.FilmCategory
	}
	return nil
}

//Request for update film category
type UpdateRequest struct {
	//api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	//Update entity film
	FilmCategor          *FilmCategory `protobuf:"bytes,2,opt,name=film_categor,json=filmCategor,proto3" json:"film_categor,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateRequest) GetFilmCategor() *FilmCategory {
	if m != nil {
		return m.FilmCategor
	}
	return nil
}

//Response to update film category
type UpdateResponse struct {
	//api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Contains number of entities have been updated
	// Equals 1 in case of successful update
	Updated              int64    `protobuf:"varint,2,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateResponse) Reset()         { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()    {}
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{6}
}

func (m *UpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateResponse.Unmarshal(m, b)
}
func (m *UpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateResponse.Marshal(b, m, deterministic)
}
func (m *UpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateResponse.Merge(m, src)
}
func (m *UpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateResponse.Size(m)
}
func (m *UpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateResponse proto.InternalMessageInfo

func (m *UpdateResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *UpdateResponse) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

//Delete request for film category
type DeleteRequest struct {
	//api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	// Contains number of entities have been deleted
	// Equals 1 in case of successful delete
	Deleted              int64    `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{7}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *DeleteRequest) GetDeleted() int64 {
	if m != nil {
		return m.Deleted
	}
	return 0
}

//Response to delete film category
type DeleteResponse struct {
	//api version
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteResponse) Reset()         { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()    {}
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{8}
}

func (m *DeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteResponse.Unmarshal(m, b)
}
func (m *DeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteResponse.Marshal(b, m, deterministic)
}
func (m *DeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteResponse.Merge(m, src)
}
func (m *DeleteResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteResponse.Size(m)
}
func (m *DeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteResponse proto.InternalMessageInfo

func (m *DeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

//Request for read all film categories
type ReadAllRequest struct {
	//api version
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAllRequest) Reset()         { *m = ReadAllRequest{} }
func (m *ReadAllRequest) String() string { return proto.CompactTextString(m) }
func (*ReadAllRequest) ProtoMessage()    {}
func (*ReadAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{9}
}

func (m *ReadAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllRequest.Unmarshal(m, b)
}
func (m *ReadAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllRequest.Marshal(b, m, deterministic)
}
func (m *ReadAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllRequest.Merge(m, src)
}
func (m *ReadAllRequest) XXX_Size() int {
	return xxx_messageInfo_ReadAllRequest.Size(m)
}
func (m *ReadAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllRequest proto.InternalMessageInfo

func (m *ReadAllRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

//Response for get all the film categories
type ReadAllResponse struct {
	//api version
	Api string `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	//List of all films
	FilmCategory         []*FilmCategory `protobuf:"bytes,2,rep,name=film_category,json=filmCategory,proto3" json:"film_category,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReadAllResponse) Reset()         { *m = ReadAllResponse{} }
func (m *ReadAllResponse) String() string { return proto.CompactTextString(m) }
func (*ReadAllResponse) ProtoMessage()    {}
func (*ReadAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_13fe395741c8317b, []int{10}
}

func (m *ReadAllResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAllResponse.Unmarshal(m, b)
}
func (m *ReadAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAllResponse.Marshal(b, m, deterministic)
}
func (m *ReadAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAllResponse.Merge(m, src)
}
func (m *ReadAllResponse) XXX_Size() int {
	return xxx_messageInfo_ReadAllResponse.Size(m)
}
func (m *ReadAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAllResponse proto.InternalMessageInfo

func (m *ReadAllResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ReadAllResponse) GetFilmCategory() []*FilmCategory {
	if m != nil {
		return m.FilmCategory
	}
	return nil
}

func init() {
	proto.RegisterType((*FilmCategory)(nil), "FilmCategory")
	proto.RegisterType((*CreateRequest)(nil), "CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "CreateResponse")
	proto.RegisterType((*ReadMessage)(nil), "ReadMessage")
	proto.RegisterType((*ReadResponse)(nil), "ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "DeleteResponse")
	proto.RegisterType((*ReadAllRequest)(nil), "ReadAllRequest")
	proto.RegisterType((*ReadAllResponse)(nil), "ReadAllResponse")
}

func init() { proto.RegisterFile("proto/film/film-service.proto", fileDescriptor_13fe395741c8317b) }

var fileDescriptor_13fe395741c8317b = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xd1, 0x6b, 0xdb, 0x3e,
	0x10, 0x26, 0x4d, 0xeb, 0xfc, 0x7a, 0x76, 0x92, 0x22, 0xca, 0x6f, 0x26, 0x30, 0x9a, 0x19, 0xc6,
	0x1a, 0xd8, 0xd4, 0x92, 0xc1, 0x18, 0x74, 0x2f, 0xa3, 0xa5, 0x50, 0xd8, 0x5e, 0xdc, 0x96, 0xb1,
	0x27, 0xa3, 0xda, 0x17, 0x4f, 0xa0, 0xd8, 0x9e, 0x24, 0x0f, 0xfa, 0xef, 0x6e, 0xff, 0xc8, 0x90,
	0x64, 0x77, 0x4e, 0x96, 0x74, 0x6c, 0x2f, 0x41, 0xf7, 0xe9, 0xbb, 0xef, 0x4e, 0xdf, 0x5d, 0x0c,
	0x4f, 0x2b, 0x59, 0xea, 0xf2, 0x64, 0xc1, 0xc5, 0xd2, 0xfe, 0xbc, 0x52, 0x28, 0xbf, 0xf1, 0x14,
	0xa9, 0xc5, 0x27, 0x47, 0x79, 0x59, 0xe6, 0x02, 0x4f, 0x6c, 0x74, 0x57, 0x2f, 0x4e, 0x34, 0x5f,
	0xa2, 0xd2, 0x6c, 0x59, 0x39, 0x42, 0xf4, 0xbd, 0x0f, 0xc1, 0x25, 0x17, 0xcb, 0x73, 0xa6, 0x31,
	0x2f, 0xe5, 0x3d, 0x79, 0x02, 0x03, 0xa3, 0x93, 0xf0, 0x2c, 0xec, 0x4d, 0x7b, 0xc7, 0xfd, 0xd8,
	0x33, 0xe1, 0x55, 0x46, 0x0e, 0x61, 0x4f, 0x73, 0x2d, 0x30, 0xdc, 0x99, 0xf6, 0x8e, 0xf7, 0x63,
	0x17, 0x90, 0x29, 0xf8, 0x19, 0xaa, 0x54, 0xf2, 0x4a, 0xf3, 0xb2, 0x08, 0xfb, 0xf6, 0xae, 0x0b,
	0x91, 0x67, 0x10, 0x48, 0x14, 0xc8, 0x14, 0x26, 0xf7, 0xc8, 0x64, 0xb8, 0xeb, 0x28, 0x0d, 0xf6,
	0x19, 0x99, 0x24, 0x47, 0xe0, 0x0b, 0x56, 0xe4, 0x35, 0xcb, 0xd1, 0xd4, 0xdd, 0xb3, 0x75, 0xa1,
	0x85, 0xae, 0x32, 0x72, 0x0a, 0x87, 0xa5, 0xe4, 0x39, 0x2f, 0x98, 0x48, 0xba, 0x4c, 0xcf, 0x32,
	0x49, 0x7b, 0xf7, 0xe1, 0x57, 0xc6, 0x0b, 0x18, 0x4b, 0x2c, 0x34, 0x13, 0x49, 0x56, 0x4b, 0x66,
	0x7b, 0x1b, 0xd8, 0xc2, 0x23, 0x07, 0x5f, 0x34, 0xa8, 0xa9, 0xdd, 0x10, 0x25, 0xd3, 0x18, 0xfe,
	0x67, 0x49, 0xe0, 0xa0, 0x98, 0x69, 0x24, 0xff, 0x83, 0x27, 0xb0, 0xc8, 0xf5, 0x97, 0x70, 0xdf,
	0xf9, 0xe1, 0x22, 0x32, 0x83, 0x03, 0x89, 0x95, 0x60, 0x29, 0x2e, 0xb1, 0xd0, 0x49, 0x5a, 0x2a,
	0x1d, 0x82, 0xcd, 0x1e, 0x77, 0xf0, 0xf3, 0x52, 0x69, 0x23, 0x61, 0xaa, 0x15, 0x79, 0xe8, 0x5b,
	0x42, 0x13, 0x19, 0x09, 0x55, 0x61, 0xca, 0x99, 0x48, 0x16, 0xc8, 0x74, 0x2d, 0x51, 0x85, 0x81,
	0x93, 0x68, 0xf0, 0xcb, 0x06, 0x26, 0x67, 0xc6, 0x22, 0xa5, 0x93, 0xba, 0xca, 0x4c, 0x9b, 0xc3,
	0x69, 0xef, 0xd8, 0x9f, 0x4f, 0xa8, 0x1b, 0x2f, 0x6d, 0xc7, 0x4b, 0x6f, 0xda, 0xf1, 0x1a, 0xfb,
	0x94, 0xbe, 0xb5, 0xec, 0xe8, 0x16, 0x86, 0xe7, 0x12, 0x99, 0xc6, 0x18, 0xbf, 0xd6, 0xa8, 0x34,
	0x39, 0x80, 0x3e, 0xab, 0xb8, 0x1d, 0xf0, 0x7e, 0x6c, 0x8e, 0x64, 0x0e, 0x43, 0x3b, 0xf6, 0xb4,
	0xd9, 0x03, 0x3b, 0x65, 0x7f, 0x3e, 0xa4, 0xdd, 0xe5, 0x88, 0x83, 0x45, 0x27, 0x8a, 0xde, 0xc0,
	0xa8, 0x95, 0x55, 0x55, 0x59, 0x28, 0xdc, 0xa0, 0x4b, 0x60, 0xd7, 0xe4, 0x58, 0xb9, 0x7e, 0x6c,
	0xcf, 0xd1, 0x5b, 0xf0, 0x63, 0x64, 0xd9, 0x47, 0x54, 0x8a, 0xe5, 0x9b, 0x92, 0x3a, 0x3b, 0xb8,
	0xd3, 0xdd, 0xc1, 0xe8, 0x06, 0x02, 0x93, 0xf9, 0x48, 0xbd, 0x7f, 0x79, 0xc7, 0x35, 0x0c, 0x9d,
	0x51, 0xdb, 0xed, 0x39, 0x85, 0xa0, 0x2b, 0xbb, 0x59, 0xd5, 0xef, 0xa8, 0x46, 0xef, 0x60, 0xd4,
	0x8a, 0x6e, 0x6d, 0x36, 0x84, 0x81, 0x9b, 0x67, 0xfb, 0xce, 0x36, 0x8c, 0xce, 0x60, 0x78, 0x81,
	0x02, 0x1f, 0x6b, 0x29, 0x84, 0x41, 0x66, 0x29, 0x0f, 0xc9, 0x4d, 0x18, 0x45, 0x30, 0x6a, 0x93,
	0xb7, 0x95, 0x36, 0x1c, 0xe3, 0xe4, 0x7b, 0x21, 0xb6, 0x56, 0x88, 0x3e, 0xc1, 0xf8, 0x81, 0xf3,
	0x37, 0x86, 0xf7, 0xff, 0x60, 0xf8, 0xfc, 0x47, 0x0f, 0x7c, 0x73, 0x7d, 0xed, 0xbe, 0x55, 0x64,
	0x06, 0x9e, 0x5b, 0x24, 0x32, 0xa2, 0x2b, 0x8b, 0x3a, 0x19, 0xd3, 0xb5, 0x0d, 0x7b, 0x0e, 0xbb,
	0xa6, 0x27, 0x12, 0xd0, 0xce, 0x0a, 0xfd, 0x4e, 0x9b, 0x81, 0xe7, 0xdc, 0xdf, 0xa0, 0xb8, 0x36,
	0x96, 0x19, 0x78, 0xce, 0x2d, 0x32, 0xa2, 0x2b, 0x9e, 0x4f, 0xc6, 0x74, 0xcd, 0xc6, 0x97, 0x30,
	0x68, 0x0c, 0x21, 0x63, 0xba, 0x6a, 0xdf, 0xe4, 0x80, 0xae, 0x79, 0x75, 0xe7, 0xd9, 0x7f, 0xe5,
	0xeb, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x33, 0x8d, 0x81, 0xa3, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FilmServiceClient is the client API for FilmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FilmServiceClient interface {
	//Create new film category
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	//Read film category
	Read(ctx context.Context, in *ReadMessage, opts ...grpc.CallOption) (*CreateResponse, error)
	//Update film category
	Update(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	//Delete film category
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	//Read all film category
	ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error)
}

type filmServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilmServiceClient(cc grpc.ClientConnInterface) FilmServiceClient {
	return &filmServiceClient{cc}
}

func (c *filmServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/FilmService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) Read(ctx context.Context, in *ReadMessage, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/FilmService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) Update(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, "/FilmService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, "/FilmService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *filmServiceClient) ReadAll(ctx context.Context, in *ReadAllRequest, opts ...grpc.CallOption) (*ReadAllResponse, error) {
	out := new(ReadAllResponse)
	err := c.cc.Invoke(ctx, "/FilmService/ReadAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilmServiceServer is the server API for FilmService service.
type FilmServiceServer interface {
	//Create new film category
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	//Read film category
	Read(context.Context, *ReadMessage) (*CreateResponse, error)
	//Update film category
	Update(context.Context, *CreateRequest) (*UpdateResponse, error)
	//Delete film category
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	//Read all film category
	ReadAll(context.Context, *ReadAllRequest) (*ReadAllResponse, error)
}

// UnimplementedFilmServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFilmServiceServer struct {
}

func (*UnimplementedFilmServiceServer) Create(ctx context.Context, req *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedFilmServiceServer) Read(ctx context.Context, req *ReadMessage) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (*UnimplementedFilmServiceServer) Update(ctx context.Context, req *CreateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedFilmServiceServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedFilmServiceServer) ReadAll(ctx context.Context, req *ReadAllRequest) (*ReadAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAll not implemented")
}

func RegisterFilmServiceServer(s *grpc.Server, srv FilmServiceServer) {
	s.RegisterService(&_FilmService_serviceDesc, srv)
}

func _FilmService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FilmService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FilmService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).Read(ctx, req.(*ReadMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FilmService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).Update(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FilmService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FilmService_ReadAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilmServiceServer).ReadAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FilmService/ReadAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilmServiceServer).ReadAll(ctx, req.(*ReadAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FilmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "FilmService",
	HandlerType: (*FilmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _FilmService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _FilmService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _FilmService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FilmService_Delete_Handler,
		},
		{
			MethodName: "ReadAll",
			Handler:    _FilmService_ReadAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/film/film-service.proto",
}
